// app/layout.tsx
import React from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';  

import NavbarWrapper from '../components/NavbarWrapper';
import Footer from '../components/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          maxWidth: '1512px',
          minHeight: '100vh',
          margin: '0 auto',
          padding: '0',
          position: 'relative',
          overflowX: 'hidden',
          overflowY: 'auto',
          backgroundColor: '#000',
        }}
      >
        {/* Renderizar Navbar en todas las páginas */}
        <NavbarWrapper />
        
        {/* Gradientes globales */}
        <div className="gradient-1"></div>
        <div className="gradient-2"></div>
        <div className="gradient-3"></div>
        <div className="gradient-4"></div>
        <div className="gradient-5"></div>
        <div className="gradient-6"></div>

        {/* Render del contenido */}
        <main className="relative z-10 ">{children}</main>

        {/* Footer en la parte inferior */}
        <Footer />
      </body>
    </html>
  );
}
